package tk.hackspace.models.repos;

/**
 * Created by terron on 28.12.15.
 */
public class QweryUtils {
    public static final String articlesBySupplierNameQwery = "SELECT ARTICLE_ID FROM SUPPLIER INNER JOIN T_HEADER ON T_HEADER.SUPPLIER_ID = SUPPLIER.ID JOIN BMECAT ON BMECAT.HEADER_HEADERID=T_HEADER.HEADER_ID JOIN TNEW_CATALOG_ARTICLE ON TNEW_CATALOG_ARTICLE.TNEW_CATALOG_ID = BMECAT.TNEWCATALOG_ID JOIN ARTICLE ON ARTICLE.ARTICLE_ID = TNEW_CATALOG_ARTICLE.ARTICLE_ARTICLE_ID WHERE SUPPLIER.SUPPLIER_NAME LIKE 'F'";
    public static final String getArticleIdByBmecatID = "SELECT ARTICLE_ARTICLE_ID  FROM BMECAT JOIN TNEW_CATALOG_ARTICLE ON BMECAT.TNEWCATALOG_ID = TNEW_CATALOG_ARTICLE.TNEW_CATALOG_ID WHERE BMECAT.ID=1";
    public static final String filterCatalogsBySupplirName = "SELECT BMECAT.ID  FROM SUPPLIER JOIN T_HEADER ON SUPPLIER.ID=T_HEADER.SUPPLIER_ID  JOIN BMECAT ON BMECAT.HEADER_HEADERID=T_HEADER.HEADER_ID WHERE SUPPLIER.SUPPLIER_NAME LIKE 'EBERO'";
}
