//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 08:32:58 PM MSK 
//


package tk.hackspace.jpa.test;

import javax.persistence.*;
import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "generatorinfo",
        "testCatalog",
        "testSupplier",

})
@XmlRootElement(name = "HEADER")
@Entity
@Table(name = "T_HEADER")
public class TestHeader {
    @Id
    @GeneratedValue
    @XmlTransient
    private Long headerId;
    @XmlElement(name = "GENERATOR_INFO")
    protected String generatorinfo;

    public TestCatalog getTestCatalog() {
        return testCatalog;
    }

    public void setTestCatalog(TestCatalog testCatalog) {
        this.testCatalog = testCatalog;
    }

    @XmlElement(name = "CATALOG", required = true)
    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    private TestCatalog testCatalog;

    @XmlElement(name = "SUPPLIER", required = true)
    @OneToOne(cascade = CascadeType.ALL)
    protected TestSupplier testSupplier;

    public TestSupplier getTestSupplier() {
        return testSupplier;
    }

    public void setTestSupplier(TestSupplier testSupplier) {
        this.testSupplier = testSupplier;
    }

    public String getGeneratorinfo() {
        return generatorinfo;
    }

    public void setGeneratorinfo(String generatorinfo) {
        this.generatorinfo = generatorinfo;
    }

    public Long getHeaderId() {
        return headerId;
    }

    public void setHeaderId(Long headerId) {
        this.headerId = headerId;
    }

    public TestHeader(String generatorinfo, TestCatalog testCatalog, TestSupplier testSupplier) {
        this.generatorinfo = generatorinfo;
        this.testCatalog = testCatalog;
        this.testSupplier = testSupplier;
    }

    public TestHeader() {

    }

    @Override
    public String toString() {
        return "TestHeader{" +
                "headerId=" + headerId +
                ", generatorinfo='" + generatorinfo + '\'' +
                ", testCatalog=" + testCatalog +
                ", testSupplier=" + testSupplier +
                '}';
    }
}
