//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 08:32:58 PM MSK 
//


package tk.hackspace.models;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "priceamount",
        "pricecurrency",
        "tax",
        "pricefactor",
        "lowerbound",
})
@XmlRootElement(name = "ARTICLE_PRICE")
@Entity
public class ArticlePrice {

    @XmlAttribute(name = "price_type", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String priceType;
    @XmlElement(name = "PRICE_AMOUNT", required = true)
    protected String priceamount;
    @XmlElement(name = "PRICE_CURRENCY")
    protected String pricecurrency;
    @XmlElement(name = "TAX")
    protected String tax;
    @XmlElement(name = "PRICE_FACTOR")
    protected String pricefactor;
    @XmlElement(name = "LOWER_BOUND")
    protected String lowerbound;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @XmlTransient
    @Column(unique = true)
    private Long id;

    public ArticlePrice() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the value of the priceType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * Sets the value of the priceType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPriceType(String value) {
        this.priceType = value;
    }

    /**
     * Gets the value of the priceamount property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPRICEAMOUNT() {
        return priceamount;
    }

    /**
     * Sets the value of the priceamount property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPRICEAMOUNT(String value) {
        this.priceamount = value;
    }

    /**
     * Gets the value of the pricecurrency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPRICECURRENCY() {
        return pricecurrency;
    }

    /**
     * Sets the value of the pricecurrency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPRICECURRENCY(String value) {
        this.pricecurrency = value;
    }

    /**
     * Gets the value of the tax property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTAX() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTAX(String value) {
        this.tax = value;
    }

    /**
     * Gets the value of the pricefactor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPRICEFACTOR() {
        return pricefactor;
    }

    /**
     * Sets the value of the pricefactor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPRICEFACTOR(String value) {
        this.pricefactor = value;
    }

    /**
     * Gets the value of the lowerbound property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLOWERBOUND() {
        return lowerbound;
    }

    /**
     * Sets the value of the lowerbound property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLOWERBOUND(String value) {
        this.lowerbound = value;
    }

}
