//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 08:32:58 PM MSK 
//


package tk.hackspace.models;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.*;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "mime"
})
@XmlRootElement(name = "MIME_INFO")
@Entity
public class MimeInfo {

    @XmlElement(name = "MIME", required = true)
    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    protected List<Mime> mime;

    @Id
    @GeneratedValue
    @XmlTransient
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MimeInfo() {
    }

    /**
     * Gets the value of the mime property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mime property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMIME().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mime }
     */
    public List<Mime> getMIME() {
        if (mime == null) {
            mime = new ArrayList<>();
        }
        return this.mime;
    }

}
