//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 08:32:58 PM MSK 
//


package tk.hackspace.models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the tk.hackspace.dtd.gen package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tk.hackspace.dtd.gen
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link ArticleOrderDetails }
     */
    public ArticleOrderDetails createARTICLEORDERDETAILS() {
        return new ArticleOrderDetails();
    }


    /**
     * Create an instance of {@link ArticleDetails }
     */
    public ArticleDetails createARTICLEDETAILS() {
        return new ArticleDetails();
    }

    /**
     * Create an instance of {@link BuyeraId }
     */
    public BuyeraId createBUYERAID() {
        return new BuyeraId();
    }

    /**
     * Create an instance of {@link SpecialTreatmentClass }
     */
    public SpecialTreatmentClass createSPECIALTREATMENTCLASS() {
        return new SpecialTreatmentClass();
    }

    /**
     * Create an instance of {@link Keyword }
     */
    public Keyword createKEYWORD() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link ArticleStatus }
     */
    public ArticleStatus createARTICLESTATUS() {
        return new ArticleStatus();
    }

    /**
     * Create an instance of {@link Mime }
     */
    public Mime createMIME() {
        return new Mime();
    }

    /**
     * Create an instance of {@link Catalog }
     */
    public Catalog createCATALOG() {
        return new Catalog();
    }

    /**
     * Create an instance of {@link DateTime }
     */
    public DateTime createDATETIME() {
        return new DateTime();
    }

    /**
     * Create an instance of {@link PriceFlag }
     */
    public PriceFlag createPRICEFLAG() {
        return new PriceFlag();
    }



    /**
     * Create an instance of {@link SupplierId }
     */
    public SupplierId createSUPPLIERID() {
        return new SupplierId();
    }

    /**
     * Create an instance of {@link Header }
     */
    public Header createHEADER() {
        return new Header();
    }



    /**
     * Create an instance of {@link Supplier }
     */
    public Supplier createSUPPLIER() {
        return new Supplier();
    }

    /**
     * Create an instance of {@link Address }
     */
    public Address createADDRESS() {
        return new Address();
    }

    /**
     * Create an instance of {@link MimeInfo }
     */
    public MimeInfo createMIMEINFO() {
        return new MimeInfo();
    }



    /**
     * Create an instance of {@link ReferenceFeatureGroupId }
     */
    public ReferenceFeatureGroupId createREFERENCEFEATUREGROUPID() {
        return new ReferenceFeatureGroupId();
    }


    /**
     * Create an instance of {@link PublicKey }
     */
    public PublicKey createPUBLICKEY() {
        return new PublicKey();
    }

    /**
     * Create an instance of {@link ArticleFeatures }
     */
    public ArticleFeatures createARTICLEFEATURES() {
        return new ArticleFeatures();
    }

    /**
     * Create an instance of {@link ReferenceFeatureGroupName }
     */
    public ReferenceFeatureGroupName createREFERENCEFEATUREGROUPNAME() {
        return new ReferenceFeatureGroupName();
    }

    /**
     * Create an instance of {@link BMEcat }
     */
    public BMEcat createBMECAT() {
        return new BMEcat();
    }

    /**
     * Create an instance of {@link TNewCatalog }
     */
    public TNewCatalog createTNEWCATALOG() {
        return new TNewCatalog();
    }

    /**
     * Create an instance of {@link Article }
     */
    public Article createARTICLE() {
        return new Article();
    }

}
