//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 08:32:58 PM MSK 
//


package tk.hackspace.models;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.*;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "supplierIds",
        "supplierName",
        "address",
        "mimeinfo"
})
@XmlRootElement(name = "SUPPLIER")
@Entity
public class Supplier {

    @XmlElement(name = "SUPPLIER_ID")
    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    protected List<SupplierId> supplierIds;
    @XmlElement(name = "SUPPLIER_NAME", required = true)
    protected String supplierName;
    @XmlElement(name = "ADDRESS")
    @ManyToOne(cascade = CascadeType.ALL)
    protected Address address;
    @XmlElement(name = "MIME_INFO")
    @ManyToOne(cascade = CascadeType.ALL)
    protected MimeInfo mimeinfo;

    @Id
    @GeneratedValue
    @XmlTransient
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Supplier() {
    }

    /**
     * Gets the value of the supplierIds property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplierIds property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplierId().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplierId }
     */
    public List<SupplierId> getSupplierId() {
        if (supplierIds == null) {
            supplierIds = new ArrayList<SupplierId>();
        }
        return this.supplierIds;
    }

    /**
     * Gets the value of the supplierName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * Sets the value of the supplierName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSUPPLIERNAME(String value) {
        this.supplierName = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return possible object is
     * {@link Address }
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value allowed object is
     *              {@link Address }
     */
    public void setADDRESS(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the mimeinfo property.
     *
     * @return possible object is
     * {@link MimeInfo }
     */
    public MimeInfo getMIMEINFO() {
        return mimeinfo;
    }

    /**
     * Sets the value of the mimeinfo property.
     *
     * @param value allowed object is
     *              {@link MimeInfo }
     */
    public void setMIMEINFO(MimeInfo value) {
        this.mimeinfo = value;
    }

}
